server:
  port: 8082
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mysecurity?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
      username: root
      password: 5252
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: true

logging:
  level:
    com:
      security:
        aries: debug
